In [231]:
import pandas as pd
import numpy as np

In [ ]:
pip 

In [232]:
# Creating a dataframe 

df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,11,7]], columns=['cgpa', 'resume_score', 'package'])
df

cgpa  resume_score  package
0     8             8        4
1     7             9        5
2     6            10        6
3     5            11        7

In [233]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [234]:
# creating weights and bias based on dimensions of input and output layers

'''
    I-------O
     \     / \
      \   /   \
       \ /     \
        \       O-------- y_hat
       / \     /
      /   \   /
     /     \ /
    I-------O   1
    
    2       2
    
    layer_dims = [2, 2, 1]
    
    Total trainable parameters = 2*2 + 2*1 + 2 + 1 = 9
'''

# Rather than random initialization, I'll initially set the weights to 0.1 and bias to 0

def initialize_parameters(layer_dims):
    np.random.seed(3)
    parameters = {}
    L = len(layer_dims)
    
    for i in range(1, L):
        parameters['W' + str(i)] = np.ones((layer_dims[i-1], layer_dims[i])) * 0.1
        parameters['b' + str(i)] = np.zeros((layer_dims[i], 1))
        
    return parameters

<>:3: SyntaxWarning: invalid escape sequence '\ '
<>:3: SyntaxWarning: invalid escape sequence '\ '
C:\Users\Pratham Gupta\AppData\Local\Temp\ipykernel_1396\3445762212.py:3: SyntaxWarning: invalid escape sequence '\ '
  '''


In [235]:
print(initialize_parameters([2, 2, 1]))
print(len(initialize_parameters([2, 2, 1])))

{'W1': array([[0.1, 0.1],
       [0.1, 0.1]]), 'b1': array([[0.],
       [0.]]), 'W2': array([[0.1],
       [0.1]]), 'b2': array([[0.]])}
4


In [236]:
# calculating the output of given neuron

def linear_forward(prev, w, b):
    z = np.dot(w.T, prev) + b
    
    return z

In [237]:
# Forward propagation

def forward(x, parameters):         # x is the input
    a = x
    L = len(parameters) // 2        # number of layers
    
    for i in range(1, L+1):
        a_prev = a
        w1 = parameters['W' + str(i)]
        b1 = parameters['b' + str(i)]
        
        print("a"+str(i-1)+": ", a_prev)
        print("w"+str(i)+": ", w1)
        print("b"+str(i)+": ", b1)
        print("--"*20)
        
        a = linear_forward(a_prev, w1, b1)
        print("a"+str(i)+": ", a)
        print("--"*20)
        
    return a, a_prev

In [238]:
df[['cgpa', 'resume_score']]

cgpa  resume_score
0     8             8
1     7             9
2     6            10
3     5            11

In [239]:
x = df[['cgpa', 'resume_score']].values[0].reshape(2,1)
x

array([[8],
       [8]], dtype=int64)

In [240]:
df[['package']]

package
0        4
1        5
2        6
3        7

In [241]:
df[['package']].values[0]

array([4], dtype=int64)

In [242]:
y = df[['package']].values[0][0]
y

4

In [243]:
parameters = initialize_parameters([2, 2, 1])
parameters

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [244]:
y_hat, a1 = forward(x, parameters)

# a0 is input ; a1 is output of first layer = [O11, O12]; a2 is output of second layer or prediction in this case

# This function is returning the prediction and the output of the last layer


a0:  [[8]
 [8]]
w1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
a1:  [[1.6]
 [1.6]]
----------------------------------------
a1:  [[1.6]
 [1.6]]
w2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
a2:  [[0.32]]
----------------------------------------


In [245]:
forward(x, parameters)

a0:  [[8]
 [8]]
w1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
a1:  [[1.6]
 [1.6]]
----------------------------------------
a1:  [[1.6]
 [1.6]]
w2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
a2:  [[0.32]]
----------------------------------------


(array([[0.32]]),
 array([[1.6],
        [1.6]]))

In [246]:
y_hat = y_hat[0][0]
y_hat

0.32000000000000006

In [247]:
a1

array([[1.6],
       [1.6]])

In [248]:
# Now we'll calculate loss and then update weights and bias

def update_parameters(parameters, y, y_hat, a1, x):     # y is the actual output ; y_hat is the predicted output ; a1 is the output of previous layer ; x is the input
    parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat) * a1[0][0])
    parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat) * a1[1][0])
    parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat))
    
    parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat) * parameters['W2'][0][0] * x[0][0])
    parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y - y_hat) * parameters['W2'][0][0] * x[1][0])
    parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat) * parameters['W2'][0][0])
    
    parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat) * parameters['W2'][1][0] * x[0][0])
    parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y - y_hat) * parameters['W2'][1][0] * x[1][0])
    parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat) * parameters['W2'][1][0])

In [249]:
X = df[['cgpa', 'resume_score']].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['package']].values[0][0]

# Parameter initialization
parameters = initialize_parameters([2,2,1])

y_hat,A1 = forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

a0:  [[8]
 [8]]
w1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
a1:  [[1.6]
 [1.6]]
----------------------------------------
a1:  [[1.6]
 [1.6]]
w2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
a2:  [[0.32]]
----------------------------------------


{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.119136]])}

In [250]:
X = df[['cgpa', 'resume_score']].values[1].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['package']].values[1][0]

y_hat,A1 = forward(X,parameters)
y_hat = y_hat[0][0]

a0:  [[7]
 [9]]
w1:  [[0.10658137 0.10658137]
 [0.10658137 0.10658137]]
b1:  [[0.00082267]
 [0.00082267]]
----------------------------------------
a1:  [[1.70612461]
 [1.70612461]]
----------------------------------------
a1:  [[1.70612461]
 [1.70612461]]
w2:  [[0.111776]
 [0.111776]]
b2:  [[0.119136]]
----------------------------------------
a2:  [[0.50054357]]
----------------------------------------


In [251]:
update_parameters(parameters,y,y_hat,A1,X)

parameters

{'W1': array([[0.11458955, 0.1168776 ],
        [0.11458955, 0.1168776 ]]),
 'b1': array([[0.0019667],
        [0.0019667]]),
 'W2': array([[0.12712927],
        [0.12712927]]),
 'b2': array([[0.13612818]])}

In [252]:
X = df[['cgpa', 'resume_score']].values[2].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['package']].values[2][0]

y_hat,A1 = forward(X,parameters)
y_hat = y_hat[0][0]

a0:  [[ 6]
 [10]]
w1:  [[0.11458955 0.1168776 ]
 [0.11458955 0.1168776 ]]
b1:  [[0.0019667]
 [0.0019667]]
----------------------------------------
a1:  [[1.83539945]
 [1.87200826]]
----------------------------------------
a1:  [[1.83539945]
 [1.87200826]]
w2:  [[0.12712927]
 [0.12712927]]
b2:  [[0.13612818]]
----------------------------------------
a2:  [[0.6074482]]
----------------------------------------


In [253]:
update_parameters(parameters,y,y_hat,A1,X)

parameters

{'W1': array([[0.12409711, 0.13272353],
        [0.12412266, 0.13276611]]),
 'b1': array([[0.00355129],
        [0.00355555]]),
 'W2': array([[0.14692424],
        [0.14731907]]),
 'b2': array([[0.15810417]])}

In [254]:
X = df[['cgpa', 'resume_score']].values[3].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['package']].values[3][0]

y_hat,A1 = forward(X,parameters)
y_hat = y_hat[0][0]

a0:  [[ 5]
 [11]]
w1:  [[0.12409711 0.13272353]
 [0.12412266 0.13276611]]
b1:  [[0.00355129]
 [0.00355555]]
----------------------------------------
a1:  [[1.98938603]
 [2.12760042]]
----------------------------------------
a1:  [[1.98938603]
 [2.12760042]]
w2:  [[0.14692424]
 [0.14731907]]
b2:  [[0.15810417]]
----------------------------------------
a2:  [[0.76382932]]
----------------------------------------


In [255]:
update_parameters(parameters,y,y_hat,A1,X)

parameters

{'W1': array([[0.13480689, 0.15628505],
        [0.13496456, 0.15661831]]),
 'b1': array([[0.00569325],
        [0.00572393]]),
 'W2': array([[0.17173654],
        [0.17385523]]),
 'b2': array([[0.18632757]])}

In [265]:
# Epoch implementation

parameters = initialize_parameters([2,2,1])
epochs = 75

loss = []
final_loss = []

for i in range(epochs):    
    
    for j in range(df.shape[0]):
            
        X = df[['cgpa', 'resume_score']].values[j].reshape(2,1)
        y = df[['package']].values[j][0]
        
        # parameter initialization
        
        y_hat, A1 = forward(X, parameters)
        y_hat = y_hat[0][0]
        
        update_parameters(parameters, y, y_hat, A1, X)
        
        loss.append((y - y_hat)**2)
    
    print("Epoch: ", i, " Loss: ", np.mean(loss) , "\n\n\n\n")
    final_loss.append(np.mean(loss))
    

for i in range(len(final_loss)):
    x = i
    print("Epoch: ", x+1, " Loss: ", final_loss[i])
parameters


a0:  [[8]
 [8]]
w1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
a1:  [[1.6]
 [1.6]]
----------------------------------------
a1:  [[1.6]
 [1.6]]
w2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
a2:  [[0.32]]
----------------------------------------
a0:  [[7]
 [9]]
w1:  [[0.10658137 0.10658137]
 [0.10658137 0.10658137]]
b1:  [[0.00082267]
 [0.00082267]]
----------------------------------------
a1:  [[1.70612461]
 [1.70612461]]
----------------------------------------
a1:  [[1.70612461]
 [1.70612461]]
w2:  [[0.111776]
 [0.111776]]
b2:  [[0.119136]]
----------------------------------------
a2:  [[0.50054357]]
----------------------------------------
a0:  [[ 6]
 [10]]
w1:  [[0.11458955 0.1168776 ]
 [0.11458955 0.1168776 ]]
b1:  [[0.0019667]
 [0.0019667]]
----------------------------------------
a1:  [[1.83539945]
 [1.87200826]]
----------------------------------------
a1:  [[1.83539945]
 [1.87200826]]
w2:  [[0.12712927]
 [0.127

{'W1': array([[-0.03233065,  0.701607  ],
        [-0.026678  ,  0.83842401]]),
 'b1': array([[0.02932977],
        [0.03823413]]),
 'W2': array([[0.37223157],
        [0.46244257]]),
 'b2': array([[0.46525268]])}